[package]
name = "rqueue"
version = "0.1.0"
authors = ["aliang <aliang2344@gmail.com>"]

[dependencies]
mio = "0.5"

[[bin]]
name = "server"
path = "src/main.rs"

[[bin]]
name = "client"
path = "src/client.rs"
